### ISSUE TITLE
blynk only buffers before error

### ISSUE THREAD

**Issue by drunkscientist** [arkhipenko/esp32-cam-mjpeg#1]
so stream displays fine in browser, works fine in vlc, blynk web link button widget works, but not the stream widget. it just buffers before saying error

**Comment by arkhipenko** [comment]
Yes, happens from time to time, and blynk authors gave up trying to fix it. I am able to restart the stream sometimes by restarting the blynk app, sometimes by stopping and starting individual project. Not reliable, agree. Can't do much about it because, as you said, it works in the browser and in VLC... If you find out how to make it work more reliable in blynk please DO let me know!

**Comment by drunkscientist** [comment]
i mean. 'time to time' would be nice, i currently cant get it to work at all, ever. but glad to know its not because im doing it wrong, at least

**Comment by arkhipenko** [comment]
Are you using the latest Blynk App? Are you on iOS or Android? I heard they work differently.

**Comment by drunkscientist** [comment]
its ios, unfortunately. really reevaluating whether im going to get another one or not since they dont seem to work with ANY of the stuff ive tried to make

**Comment by arkhipenko** [comment]
I just tested the latest Blynk version, and yes, it completely stopped working. I will hit them with a bug report again.

**Comment by drunkscientist** [comment]
legit thank you, now i can stop banging my head against a wall for at least little bit and work on some other part of the project

**Comment by arkhipenko** [comment]
https://community.blynk.cc/t/video-widget-stopped-working-on-version-2-28-7/52500

**Comment by arkhipenko** [comment]
Did you try 2.27.28? It still works for me on Android at least.

**Comment by drunkscientist** [comment]
2.26.6 is the only thing available on my iphone. i did find an old galaxy s4 to test with, but i think its a little old as i couldnt find the blynk app from the device, i had to google it from pc and go the "install to device" route to get it there. it is 2.27.28, but it does not work unfortunately. what is interesting is the 'weblink' button (which DOES work on ios) does not work either, i have to click the up arrow to open the page in an external browser in order to see the stream (which then does display in the browser)

**Comment by arkhipenko** [comment]
Sorry about all your trouble... Maybe the new version of Blynk will be more stable.
