### ISSUE TITLE
Camera error

### ISSUE THREAD

**Issue by JabberwockPL** [arkhipenko/esp32-cam-mjpeg#6]
I have an odd problem: the serial report shows:
E (492) camera: Camera probe failed with error 0x105(ESP_ERR_NOT_FOUND)

Descriptions of this error indicate a hardware problem, however, when I use a different library (e.g. for JPEG streaming), the camera works fine. What could be the reason for that? I notice that just before the error the LED blinks, could it be a powering problem?

**Comment by arkhipenko** [comment]
Did you select your model correctly here?
https://github.com/arkhipenko/esp32-cam-mjpeg/blob/83b3475742643d6d323443e91726034329d269e2/esp32_camera_mjpeg.ino#L19

**Comment by JabberwockPL** [comment]
I thought I did, but actually no... Sorry about that! Now it works great!
